name: bikram_sambat
description: A dart package that handles working with Nepali Bikram Sambat dates
version: 1.0.1
homepage: https://github.com/kedarkarkee/bikram_sambat
repository: https://github.com/kedarkarkee/bikram_sambat.git
issue_tracker: https://github.com/kedarkarkee/bikram_sambat/issues
documentation: https://github.com/kedarkarkee/bikram_sambat/blob/main/README.md

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
# dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

topics:
  - bikram-sambat
  - ad-bs
  - nepali-date
  - nepali-time
  - nepali-calendar
